# Print all subsequences of a string

# Given a string, we have to find out all subsequences of it. A String is a subsequence of a given String, that is generated by deleting some character of a given string without changing its order.
# Examples: 

# Input : abc
# Output : a, b, c, ab, bc, ac, abc

# Input : aaa
# Output : a, aa, aaa

def subsequences(nums):
    x = 0
    y = 1
    sequence = set()
    sequence.add(nums)
    while True:
        if x < len(nums):
            if y < len(nums):
                sequence.add(nums[x]+nums[y])
                sequence.add(nums[x:y+1])
                y = y + 1
            else:
                sequence.add(nums[x])
                x = x + 1
                y = x + 1     
        else:
            break
    print(sequence)

for value in ['abc','aaa','aabc']:
    print(f'Input is {value}')
    subsequences(value)